### ISSUE TITLE
Migrate from Parcel to Webpack

### ISSUE THREAD

**Issue by kevinydhan** [Kedyn/fusliez-notes#63]
Here is a running checklist of Webpack's functionality:

## Asset creation:
- [x] Webpack should create `index.html` (Addressed in #72).
- [x] Webpack should create favicon sets.
- [x] Webpack should create `manifest.webmanifest` *(?)*.
- [ ] Webpack should create `robots.txt`*(?)*.

<br>

## Minification:
- [x] Webpack should minify `.html` files for production builds (Addressed in #72).
- [x] #60: Webpack should minify `.js` files for production builds (Addressed in #72).
- [x] Webpack should minify `.json` files for production builds (Addressed in #72).

<br>

## Optimizations:
- [x] #60: Webpack should optimize images.
- [x] Webpack should code split deferred components *(?)*.
- [ ] Webpack should chunk third-party packages *(?)*.

<br>

## Development:
- [x] Webpack should spin up a development server on http://localhost:1234 (Addressed in #72).
- [x] Webpack should automatically open the default browser to the url (Addressed in #72).
- [x] Webpack should create source maps (Addressed in #72).

**Comment by Kedyn** [comment]
I was not leaving source maps for production, but recently read something that made sense to me: "The web is a better place when we allow others to learn from our work"

**Comment by kevinydhan** [comment]
@Kedyn I currently omitted source maps in production builds, but can change it if you want to include it.
